version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - communitycategories
  - ekoru
  - EKORU
  - servicecategories
  - storecategories
  - subcat
  - subcategorías
  - Subcategorías
  - tiktok
ignoreWords: []
import: []
